import os
import uuid
import json
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

app = Flask(__name__)

AUDIT_LOG_PATH = "audit_log.json"

# --- Signal 1: Groq LLM Semantic Analysis --- verified

def analyze_semantic_signal(text):
    """
    Sends text to the Groq LLM and returns a float between 0.0 (human) and 1.0 (AI).
    The model is forced to return a raw JSON object: {"ai_probability": <float>}.
    Falls back to 0.5 if the API call or JSON parsing fails.
    """
    try:
        client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            response_format={"type": "json_object"},
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an objective AI-content detection engine. "
                        "Analyze the provided text and estimate the probability that it was generated by an AI model. "
                        "Consider semantic predictability, tonal uniformity, repetitive phrasing, and common AI transition patterns. "
                        "You must respond with ONLY a valid JSON object in this exact format: "
                        '{"ai_probability": <float between 0.00 and 1.00>} '
                        "Do not include any explanation, markdown, or additional text."
                    ),
                },
                {
                    "role": "user",
                    "content": text,
                },
            ],
        )

        raw_content = response.choices[0].message.content
        parsed = json.loads(raw_content)
        score = float(parsed["ai_probability"])

        # Clamp to valid range in case the model drifts slightly outside [0, 1] - verified
        return max(0.0, min(1.0, score))

    except Exception as e:
        app.logger.error(f"analyze_semantic_signal failed: {e}")
        # Neutral fallback — avoids a hard crash but flags the uncertainty - verified
        return 0.5


# --- Audit Log Helpers --- verified

def read_audit_log():
    """Reads the audit log file and returns a list of entries. Returns [] if the file doesn't exist."""
    if not os.path.exists(AUDIT_LOG_PATH):
        return []
    with open(AUDIT_LOG_PATH, "r") as f:
        return json.load(f)


def write_audit_log(entries):
    """Writes the full entries list back to the audit log file as valid JSON."""
    with open(AUDIT_LOG_PATH, "w") as f:
        json.dump(entries, f, indent=2)


# --- Routes --- verified

@app.route("/submit", methods=["POST"])
def submit():
    """
    Accepts JSON: {"text": str, "creator_id": str}
    Runs Signal 1 (Groq LLM), logs the result, and returns an attribution verdict.
    """
    data = request.get_json(silent=True)

    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Request body must include 'text' and 'creator_id'."}), 400

    text = data["text"]
    creator_id = data["creator_id"]

    # Generate a unique identifier for this submission - verified
    content_id = str(uuid.uuid4())

    # Signal 1: LLM semantic score - verified
    llm_score = analyze_semantic_signal(text)
    print(f"[DEBUG] Raw Groq LLM score for content_id {content_id}: {llm_score}")

    # Milestone 3 placeholders — Signal 2 and full scoring added in Milestone 4
    confidence = llm_score
    attribution = "likely_ai" if confidence > 0.50 else "likely_human"
    label = "PLACEHOLDER_LABEL"

    # Build and persist the audit log entry
    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "status": "classified",
    }

    entries = read_audit_log()
    entries.append(log_entry)
    write_audit_log(entries)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
    }), 200


@app.route("/log", methods=["GET"])
def get_log():
    """Returns all audit log entries as {"entries": [...]}."""
    entries = read_audit_log()
    return jsonify({"entries": entries}), 200


if __name__ == "__main__":
    app.run(port=5001, debug=True)
