import os
import uuid
import json
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

app = Flask(__name__)

AUDIT_LOG_PATH = "audit_log.json"

# --- Signal 1: Groq LLM Semantic Analysis --- verified

def analyze_semantic_signal(text):
    """
    Sends text to the Groq LLM and returns a float between 0.0 (human) and 1.0 (AI).
    The model is forced to return a raw JSON object: {"ai_probability": <float>}.
    Falls back to 0.5 if the API call or JSON parsing fails.
    """
    try:
        client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            response_format={"type": "json_object"},
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an objective AI-content detection engine. "
                        "Analyze the provided text and estimate the probability that it was generated by an AI model. "
                        "Consider semantic predictability, tonal uniformity, repetitive phrasing, and common AI transition patterns. "
                        "You must respond with ONLY a valid JSON object in this exact format: "
                        '{"ai_probability": <float between 0.00 and 1.00>} '
                        "Do not include any explanation, markdown, or additional text."
                    ),
                },
                {
                    "role": "user",
                    "content": text,
                },
            ],
        )

        raw_content = response.choices[0].message.content
        parsed = json.loads(raw_content)
        score = float(parsed["ai_probability"])

        # Clamp to valid range in case the model drifts slightly outside [0, 1] - verified
        return max(0.0, min(1.0, score))

    except Exception as e:
        app.logger.error(f"analyze_semantic_signal failed: {e}")
        # Neutral fallback — avoids a hard crash but flags the uncertainty - verified
        return 0.5


# --- Signal 2: Stylometric Sentence Length Variance ---

def calculate_stylometric_variance(text):
    """
    Splits text into sentences, counts words per sentence, and computes variance.
    Maps variance to a 0.0 (high variance / human) to 1.0 (low variance / AI) scale.
    Returns 0.5 as a neutral fallback for inputs too short to analyze reliably.
    """
    # Split on sentence-ending punctuation while keeping the delimiter attached
    import re
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    sentences = [s for s in sentences if s.strip()]

    # Not enough sentences to compute meaningful variance — return neutral score
    if len(sentences) < 2:
        return 0.5

    word_counts = [len(s.split()) for s in sentences]
    n = len(word_counts)
    mean = sum(word_counts) / n
    variance = sum((c - mean) ** 2 for c in word_counts) / n

    # Normalize: clamp raw variance against a practical ceiling (100 word^2)
    # so that very long texts don't produce outlier floats.
    MAX_VARIANCE = 100.0
    normalized_variance = min(variance, MAX_VARIANCE) / MAX_VARIANCE

    # Invert: high variance → low score (human); low variance → high score (AI)
    return round(1.0 - normalized_variance, 4)


# --- Audit Log Helpers --- verified

def read_audit_log():
    """Reads the audit log file and returns a list of entries. Returns [] if the file doesn't exist."""
    if not os.path.exists(AUDIT_LOG_PATH):
        return []
    with open(AUDIT_LOG_PATH, "r") as f:
        return json.load(f)


def write_audit_log(entries):
    """Writes the full entries list back to the audit log file as valid JSON."""
    with open(AUDIT_LOG_PATH, "w") as f:
        json.dump(entries, f, indent=2)


# --- Routes --- verified

@app.route("/submit", methods=["POST"])
def submit():
    """
    Accepts JSON: {"text": str, "creator_id": str}
    Runs Signal 1 (Groq LLM), logs the result, and returns an attribution verdict.
    """
    data = request.get_json(silent=True)

    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Request body must include 'text' and 'creator_id'."}), 400

    text = data["text"]
    creator_id = data["creator_id"]

    # Generate a unique identifier for this submission - verified
    content_id = str(uuid.uuid4())

    # Signal 1: LLM semantic score
    llm_score = analyze_semantic_signal(text)
    print(f"[DEBUG] Groq LLM score:        {llm_score}")

    # Signal 2: Stylometric variance score
    stylometric_score = calculate_stylometric_variance(text)
    print(f"[DEBUG] Stylometric score:     {stylometric_score}")

    # Weighted combination formula: Final = (LLM * 0.6) + (Stylometric * 0.4)
    confidence = round((llm_score * 0.6) + (stylometric_score * 0.4), 4)
    print(f"[DEBUG] Combined confidence:   {confidence}")

    # Threshold-based attribution
    if confidence <= 0.39:
        attribution = "likely_human"
    elif confidence <= 0.70:
        attribution = "uncertain"
    else:
        attribution = "likely_ai"

    label = "PLACEHOLDER_LABEL"

    # Build and persist the audit log entry
    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
        "status": "classified",
    }

    entries = read_audit_log()
    entries.append(log_entry)
    write_audit_log(entries)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
        "label": label,
    }), 200


@app.route("/log", methods=["GET"])
def get_log():
    """Returns all audit log entries as {"entries": [...]}."""
    entries = read_audit_log()
    return jsonify({"entries": entries}), 200


if __name__ == "__main__":
    app.run(port=5001, debug=True)
